// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulltaawgqeqngelehtzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsbHRhYXdncWVxbmdlbGVodHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzQxNjEsImV4cCI6MjA3MTM1MDE2MX0.IUprQezEz_HNXuj6Sks0PZjCpA-2FDX_b8l1HHggYgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});